name: money_calculator_v2
version: 1.0.0+1
publish_to: none
description: A Flutter application for calculating hosehold income and expensies.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: 4.3.4
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

