name: money_calculator_v2
version: 1.0.0+1
publish_to: none
description: A Flutter application for calculating hosehold income and expensies.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.4.0
  get: 4.3.4
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  flutter:
    sdk: flutter
  spaces: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

