name: money_calculator_v2
version: 1.0.0+1
publish_to: none
description: A Flutter application for calculating hosehold income and expensies.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  flutter:
    sdk: flutter
  get: ^4.3.7
  get_storage: ^2.0.3
  spaces: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/bg1.png
    - assets/img/logo_sm.png
    - assets/img/logo_white_sm.png

