name: money_calculator_v2
version: 1.0.0
publish_to: none
description: A Flutter application for calculating hosehold income and expensies.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.5.3
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  get: ^4.3.8
  get_storage: ^2.0.3
  responsive_builder: ^0.4.1
  spaces: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/bg1.png
    - assets/img/logo.png
    - assets/img/logo_sm.png
    - assets/img/logo_white_sm.png
    - assets/img/money.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo_sm.png"
